### ISSUE TITLE
Ethereumpools.info not showing data

### ISSUE THREAD

**Issue by PizBernina** [alrevuelta/eth-metrics#24]
Seems like http://34.117.66.78/d/ox1NIwf7k/ethereumpools-public?orgId=2 is not showing data anymore. Has been like this for a few days now.

**Comment by alrevuelta** [comment]
Thanks for reporting it. We are having some issues with the beacon node. Will be fixed soon.

**Comment by alrevuelta** [comment]
Fixed! Feel free to report it on [Twitter](https://twitter.com/EthereumPools) next time :)
