### ISSUE TITLE
"No Data" - metrics not shown

### ISSUE THREAD

**Issue by PizBernina** [alrevuelta/eth-metrics#41]
Seems like all metrics but the price are gone
![image](https://user-images.githubusercontent.com/47326745/212628414-89e88614-e521-4b20-978a-2b9bc4e0e0be.png)

**Comment by alrevuelta** [comment]
Hi, thanks! This is a known issue. The node is behind sync and will take 1/2 days to sync to latest head. See sync distance in the lower part.
