### ISSUE TITLE
EL & CL endpoints

### ISSUE THREAD

**Issue by PizBernina** [alrevuelta/eth-metrics#42]
Hi all,

Any chances you would also show the endpoints you use? 
https://github.com/attestantio/go-eth2-client/api/v1
Is currently private it seems.

**Comment by alrevuelta** [comment]
We run our own nodes, so we use our own endpoints.

https://github.com/attestantio/go-eth2-client/ is a library that allows to access the consensus endpoint from golang, but its not an "endpoint" per se.
